### ISSUE TITLE
Events - Screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#108]
Could we show all events within x miles of current location? 50 miles? Users might want it to show events within the current extent of the map...

I'm open to whatever makes the most sense and is relatively easy to implement.

**Comment by RyanTG** [comment]
I think at this point like 99% of the events we list on the site are pulled from IFPA. What if, instead of pulling IFPA data, we just linked to their site. Like https://www.ifpapinball.com/calendar/lat=yourlat,lon=yourlon,radius=50

(That's not a real link.) 

Because on the new app, users will be regionless and so showing locations within 50 miles of a user would require pulling the _entire_ IFPA calendar.

Just a thought. Events are a hassle..

**Comment by bpoore** [comment]
Sure, if we can make a request to the IFPA in that format, sounds good! I don't know how much this feature is used with the app- we can label the screen so that users know that it's coming from the IFPA website, so they are sure to go there to add events and whatnot.

**Comment by RyanTG** [comment]
The current version of the IFPA API does _not_ support lat/lon+radius search. And there aren't URLs like what I described above.

So, I don't know how we could show people events that are near them. Maybe there's something obvious that I'm missing. If either @bpoore or @scottwainstock has ideas, I'm all eyes.

In the meantime I'm thinking that we can't use the pbm events feature, and instead need to simply say on the page, "Looking for pinball events? Check the IFPA calendar"

**Comment by bpoore** [comment]
Hmm. For now, we could use the city/state of the location nearest to the user to perform the search within X number of miles? That might not be the best solution for international users, but it seems like that could work for US users for now?

**Comment by RyanTG** [comment]
Yeah, that is a neat idea. 

I asked Brian this in the email yesterday, but he didn't answer: Do we need to store all this data on our own server, and access it from there, or can we access it on the fly from the IFPA server?

If the former, then we'd need to regularly pull the _entire_ ifpa calendar dataset, right?

**Comment by bpoore** [comment]
I think it depends on how fast we want that screen to come up and how many requests we can make with an API key to their API. We could make a request to their API when a user goes to the event screen. If we did that, we wouldn't have to hold any of the calendar on a server and the data would always be the current data they have on their site. I haven't looked into how we are dealing with events on the site or in the current app.

**Comment by RyanTG** [comment]
Right now we're pulling events once a day from the IFPA API. Each region of ours has a central lat/lon, and we use that lat/lon to say, "[pull all events that are within 100 miles of each region's lat/lon](https://github.com/scottwainstock/pbm/blob/master/lib/tasks/import_ifpa_tournaments.rake)". 

So we store the events that are within 100 miles of each of the 99 regions. And then a user can look up the events for that region, a la https://pinballmap.com/portland/events

Our admins can also add events manually, but MOST do not. 

But the user won't be in a region with the new app, so I didn't know what to do.

**Comment by bpoore** [comment]
An option for now could be to use the find nearest region using <a href="https://pinballmap.com/api/v1/docs/1.0/regions/closest_by_lat_lon.html">this</a>?

**Comment by RyanTG** [comment]
Status update: Brian mentioned that we could try pulling _directly_/_dynamically_ from their api. 

And: 
```The current API has a calendar search that you can provide the address + radius, but it won't accept lat/lon. I'll add that to the v2. ```
So I guess we wouldn't be able to use our user's lat/lon. We'd have to convert their lat/lon to an address?

**Comment by bpoore** [comment]
That could be an option. If we are trying to dynamically request from the IFPA calendar, we would want to have 'guessed' an address for the user prior to making the request since this would require a request to the PBM API, so I would probably include that in the app set-up when we determine a user's location.

My initial thought was to grab the address of the location nearest to them until their API supports receiving lat/lon. It won't be perfect, but if we're going with a 50 mile radius, it seems like it could be close enough?

**Comment by RyanTG** [comment]
Yeah, that seems like it would be close enough!

We'll see if people eventually complain that, "I want to see events in OTHER places." I guess if they say that, we can be like, "use the ifpa calendar!"

**Comment by bpoore** [comment]
f84196bfb216d6cc581e8fc3239d95948fea724e

I got kind of fancy with determining if we need to geocode the map location or not. If there are any locations in the app state, we use the first one to pass as the address to the IFPA API... otherwise, we need to geocode the lat/lon to find an appropriate address to pass to the IFPA. I didn't notice a significant speed increase in removing the geocode step, but it doesn't hurt to not make that request if we don't need to!

These are the fields and parameters we have available to us: 
<img width="699" alt="Screen Shot 2019-04-10 at 5 32 31 PM" src="https://user-images.githubusercontent.com/7720282/55923843-36a0d500-5bbc-11e9-8464-6b7e4d28b7d6.png">

**Comment by RyanTG** [comment]
I did some initial styling - but didn't touch the flatlist container yet. Do you think it looks too redundant to have "Nearby Events" in the header and also a page title right below that (page title says, "Upcoming Events (within 50 miles)")?

I was also thinking of including some text that says that the events come from the IFPA calendar.

I think we should include these fields:
- private_flag=N. Don't display this field - but can we limit the results to only N (I'm guessing that's for public or private events? We only want to show public events)?
- tournament_name
- address1
- city
- state
- zip
- website
- start_date
- end_date

What do you think?

**Comment by bpoore** [comment]
This sounds good. We can filter out non-public events. I'm confused what those would be though because I was under the impression IFPA tournaments had to be open to everyone.

We currently have everything else on your list other than the end_date. Seems like the end_date will only make sense for multi-day events? I'm not sure how we would like to have that look?

Currently the website is linked in the tournament name like on the site.

**Comment by RyanTG** [comment]
Yeah, only makes sense for multi-day events. On the website we do end dates like this:

"start_date" && if (end_date == start_date) ? "" : " - end_date"

(not real syntax, but that's the logic)

So the result is like:

without an end_date: 5/03/2019

with an end_date: 5/03/2019 - 5/05/2019

**Comment by RyanTG** [comment]
I added that logic, and it seems to work. https://github.com/bpoore/pbm-react/pull/163/commits/ebbc1ce4836df1d938c34c5dbccee46395942933

@bpoore Are you able to change the date format? So it uses the same format as https://github.com/bpoore/pbm-react/blob/master/app/screens/LocationDetails.js#L224 I was afraid to try it.

**Comment by bpoore** [comment]
7aaa93f424cb37ef87de9fa1f5f1001881020b20

**Comment by RyanTG** [comment]
I'm still seeing the old date format. It's like YYYY-MM-DD right now.

**Comment by bpoore** [comment]
I see this on master with the simulator and on the Android device currently 🤷‍♀️ 

<img width="428" alt="Screen Shot 2019-04-16 at 1 21 54 AM" src="https://user-images.githubusercontent.com/7720282/56193715-220e7380-5fe6-11e9-9917-ca2b42bceeda.png">

**Comment by RyanTG** [comment]
I'm an idiot. Didn't pull upstream.
