### ISSUE TITLE
Speed up response time when you click "Add Machine"

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#111]
The lag will be pretty confusing to users.

**Comment by RyanTG** [comment]
`one to get the location details with the newly added machine` This occurs when the "Add Machine" button is clicked, or when the actual machine name is clicked to add the machine to the location? To clarify just in case: this issue is referring to the "+ Add Machine" button that's on the Location Details screen.

This is probably a really simplistic response, but my first thought was, "but it's not slow on the website, so what's different there?"

Are we redownloading the entire machine list each time that button is clicked?

**Comment by bpoore** [comment]
Apologies, I was talking about the process of after confirming to add a machine to a location, first a POST request takes place to add the machine, but then a GET takes place to have the newly added machine show up on the LocationDetails screen. 

No, we are not making any requests when clicking on "+ Add Machine", all the machines are stored in the local app state. It's possible that the list is large enough that it's causing some delay... I was hoping that since that list in the scheme of things isn't really that big that it wouldn't cause problems for us, but perhaps that's the issue. I can try mocking up a smaller list of machines to see if that makes a difference.

**Comment by bpoore** [comment]
Unfortunately we had to dump the out-of-box style ListItem, but the speed is fixed and we're ready to style the list 8389159c0a0f4edb2a181f23bd4b756c61769057

I got the `Done` button added back, but kept the running tally of how many machines have been selected. Feel free to keep or toss whatever you'd like of that stuff or if I can help make anything different.

**Comment by RyanTG** [comment]
Great!
