### ISSUE TITLE
Login/signup pages are displaying an empty header - should have no header

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#13]
It almost seems like ALL pages have a space up top for a header. But some should not!

**Comment by bpoore** [comment]
Found the fix for this and applied it to signuplogin, signup and login. Styles will need to be updated with this new discovery. Leaving issue open until styles can be updated from this change. We can have the background image taking up the entire screen and move the content down or move everything down.

**Comment by RyanTG** [comment]
Sweet! I’ll work on the styles. I know on some of those pages I’m
using flexbox to vertically align to the center. But I’ll
doublecheck all that.
When your commit is done, can you paste the commit link in here, just so
I can have it as a reference?

On Fri, Aug 10, 2018, at 5:43 PM, Beth Poore wrote:
> Found the fix for this and applied it to signuplogin, signup and
> login. Styles will need to be updated with this new discovery. Leaving
> issue open until styles can be updated from this change. We can have
> the background image taking up the entire screen and move the content
> down or move everything down.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/bpoore/pbm-react/issues/13#issuecomment-412238481

**Comment by bpoore** [comment]
5c83a21aaaeb71a5e2e6a2ec35f1061ddd7b707f
