### ISSUE TITLE
If I zoom in on an area, the zoom level automatically changes when the locations load

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#19]
I'm having trouble zooming in close. If I zoom in, the map automatically zooms back out when it loads locations. Can you replicate this?

Start by zooming out far, and then zooming back in.

**Comment by bpoore** [comment]
Yes, I see this as well. This is happening because we are updating lat and lon in state, but the lat and lon deltas are currently static values. I will look into options of how to deal with this... I don't think having the google map act properly will be an issue, it's correlating the zoom to the distance we're covering in the map view that will be a larger issue to deal with.

**Comment by bpoore** [comment]
@RyanTG 29df72defa4d6c6a671c4194cb6841f04e86a92e

This needs more refinement over time as the query for machines isn't updating beyond the 5 miles set as the default query radius, but now the map will zoom in and out appropriately at least.

**Comment by RyanTG** [comment]
I'm not sure if this commit caused it, but the "loading..." text doesn't disappear after the map pins load. It just stays there forever.

**Comment by bpoore** [comment]
This fixes that 4e4dbd000204eeec10fbe09b0db4bcbb400ddb93. There was a ternary statement I didn't like having to have in there... I guess it needs to be that way for the Loading indicator to go away though, so it's back.
