### ISSUE TITLE
Make "region" an autocomplete option

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#190]
We have about 100 regions on the site. And people might still want to quickly bring up all locations within a region.

So, similar to our City search autocomplete, could we have a Region search autocomplete? I don't know the endpoint offhand, but we certainly have it.

In the autocomplete it would look like "Los Angeles (Region)"

When chosen, it would load a map showing all locations within that region. Sometimes the map will be too zoomed out to show new results when you pan around. But users could just zoom in and then pan.

**Comment by bpoore** [comment]
I see the endpoint for all regions (http://pinballmap.com/api/v1/regions.json). We can pick up the regions when the app fires up like we do machines, operators, etc. 

I imagine this working like other search results where the lat/lon coordinates are used to go to the region at a default zoom of 0.1 (which roughly correlates to the 5 mile radius).

I don't think the endpoint to grab all the information for a region would work well with our regionless map- as soon as the location was nudged, a new search for the current visible map area would be fired off. With that being a consideration, would this autocomplete provide more information than searching for a city? 

It could be feasible to load up data by region, but it would require some thought with regard to how to rework the default behavior of the map to facilitate the ability to switch between contexts of region and regionless.

**Comment by bpoore** [comment]
I just read the email where this came up as an issue.

I do think a region view is possible, but I do think it will be a significant amount of work / a lot of thought should go into how the UX of being able to switch between things would work. This would basically be a different app than the one we've developed with regionless as the focus. 

If we can think about ways to still have the app be regionless but meet the needs of this use case, we might be better off in the end.

**Comment by RyanTG** [comment]
I was envisioning it so that instead of 

> I imagine this working like other search results where the lat/lon coordinates are used to go to the region at a default zoom of 0.1 (which roughly correlates to the 5 mile radius).

It would not use a default zoom, but would fit all the locations for that region into the mapview. But if we have to use the default map zoom, then no it doesn't provide a whole lot more information than a city search. 

Except that many regions aren't cities, per se, but are states (or parts of states) or countries. So if users are used to seeing all locations in "Southern Florida" then it's a lot more work for them to use the app and do a city-by-city search to see those results.

I wrote that prior to your second comment. We should chat about this more. I didn't realize this would be such a shift in scope. I just saw it as a request to "show these 20 locations on a map," but it's still the same regionless map.

**Comment by bpoore** [comment]
Hmm... yeah, let's keep thinking and talking. The nice thing about the `regions` are that there are finite number of them. We could bump up the search radius and view upon selection of regions where appropriate (Japan, S. Florida, etc). It gets a bit tricky if we want to show more than 100 miles on the screen initially because we've set that up as the maximum zoom where a search can still occur.... we might be able to do some trickery that if there are fewer than X locations in the view, allow further zoom. I would need to check on the max radius supported by `https://pinballmap.com/api/v1/docs/1.0/locations/closest_by_lat_lon.html`. This may have to be bumped up to support what's being talked about.

**Comment by RyanTG** [comment]
We recently added a field called "effective_radius" for each region. I populated it using rough estimates of how big I thought the region was. 

Each region also has a lat and lon field which represents the centerpoint of the region. 

Could the "region" search essentially be "That region lat/lon zoomed out enough to basically fit the effective radius"?

If it's past the max zoom, maybe we could get it to still _initially_ load all the locations, but the user would need to then zoom within the max zoom if they want to scroll around and see "new" results.

**Comment by bpoore** [comment]
Sounds good to me. We will need to boost `https://pinballmap.com/api/v1/docs/1.0/locations/closest_by_lat_lon.html` to support a radius of greater than 50 miles for this, but otherwise, from the app, that's something we could get to easily. 

https://github.com/scottwainstock/pbm/blob/master/app/controllers/api/v1/locations_controller.rb#L11

In the app, the default max zoom will protect us from allowing a user to zoom out and make absurd requests except for the cases we're talking about here with the regions. I don't know if we're worried about allowing anyone to make requests with a radius of 350 miles from postman etc, as I think there's room for concern about crashing the server with requests of that size. That's something @ssw will have to chime in about.

**Comment by bpoore** [comment]
@ssw you can disregard the last comment. Now that I'm into it, I see I can plug in whatever values I need for the search radius and it's working. This will be a really neat feature.

**Comment by bpoore** [comment]
@RyanTG d6cfd0aea3f28c8b15a90c13b7ec8e026d61c528
