### ISSUE TITLE
Location arrow display issues on Map.js

### ISSUE THREAD

**Issue by metroshica** [bpoore/pbm-react#221]
If the name of a location is longer, the arrow for the location's label is either cutting off or not showing at all.

Partially cut off:
![image](https://user-images.githubusercontent.com/7684916/59176918-534f7f80-8b0f-11e9-9f34-38fba61d618c.png)

Not showing at all:
![image](https://user-images.githubusercontent.com/7684916/59176927-5b0f2400-8b0f-11e9-88d7-89f97fc17b1a.png)

**Comment by RyanTG** [comment]
Thanks. I feared this would be the case. The way we’re displaying map markers is kind of a hack, because we couldn’t get the markers to display at a consistent size across all devices. 

So the hack involves setting a width/height of the marker. And then we set a max/min width for the infowindow. But it needs further adjustment.

**Comment by RyanTG** [comment]
This is discouraging. 

Given our method of displaying the marker, there are constraints when dynamically setting the width of the callout (aka infowindow). One is that the height behaves strangely, and will grow too tall. Only way I found to fix that issue is to set a fixed height. If a location name is ever more than 2 lines, then we're screwed. I found some long names, and they were never more than 2.

https://github.com/bpoore/pbm-react/pull/219/commits/893496f8dc4aed60c5bbe225cdc42ca6f80bc9a6

All in all, it's not horrible, and it looks ok (the content is vertically justified). But I really don't like having to hardcode the height and the position of the arrow icon.

Reference (no solution): https://github.com/react-native-community/react-native-maps/issues/1959
