### ISSUE TITLE
Map infowindow discussion 

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#23]
![331cf136-0a48-4ff4-8bd7-e39911464666](https://user-images.githubusercontent.com/632682/44961859-f31b1580-aecc-11e8-9fd1-cff9a4cab06b.png)
In general, I think having an infowindow popping up from the map pin doesn’t look great on mobile (not just on our app, but on all apps).

I was using google maps today and saw that they don’t do that, but instead load a container that’s positioned on the bottom of the map that shows the location info. So I’m wondering if you think something that could work for us. See the screenshot of google maps. 

Problem is I don’t think this would work with the little slideshow type thing that is supposed to be at the bottom. Unless we somehow fit in both. 

Anyway, just a thought.

**Comment by bpoore** [comment]
I agree the infowindow we currently have does not look right on mobile. I'm not sure how this would play with the slideshow as this would take up a lot more real estate on the screen. I'm wide open to solutions to this, but my initial inclination is that the slideshow card would have enough information available for someone to decide if they wanted to click on the card to go to the location details page to see all the information about a location and otherwise a significant portion of the map will still be visible to the user when clicking on pins.
