### ISSUE TITLE
Opening logo much smaller on Android

### ISSUE THREAD

**Issue by metroshica** [bpoore/pbm-react#236]
I didn't realize this was a difference until I had a coworker open the app on iOS. The pinball map logo on opening is much smaller on my Android device than on iOS. Not that big of a deal but it looks much nicer on iOS so it may be worth trying to get these to match. Here's what it looks like on my device when opening the app:
![Logo](https://user-images.githubusercontent.com/7684916/59795866-7d383d00-9299-11e9-9ddc-68ed38fbb459.png)

**Comment by RyanTG** [comment]
Yeah, known issue. It's on my lists here, https://github.com/bpoore/pbm-react/issues/121 and as you can see I crossed it out because I couldn't figure it out and gave up.

It's full screen in Android Expo, but not in the builds. This line should do it https://github.com/bpoore/pbm-react/blob/master/app.json#L67
I believe it's a known Expo bug.

**Comment by RyanTG** [comment]
It looks like this will be fixed when we upgrade to Expo 33.

https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c?gi=f2d0fac7c96f
```We’ve corrected behavior of splash screen image based on resizeMode in Android standalone apps. The behavior that was previously called cover is now properly called contain and vice versa. You may need to switch this setting in your app.json.```
We plan to upgrade soon.
