### ISSUE TITLE
Add comma seperator at thousand marks when entering scores

### ISSUE THREAD

**Issue by davidrs** [bpoore/pbm-react#293]
When entering and viewing high scores it would be helpful if the text field displayed ',' between the thousand marks.

9,000,000 instead of 9000000

Will make it easier to enter scores correctly and quickly skim others scores.

If I have some time I'm happy to take a try and this fix.

Happens in stream and when submitting a new score:

![Screenshot_20200313-141500](https://user-images.githubusercontent.com/1407489/76661197-05e9be00-6538-11ea-815b-cc9c05369109.png)

![Screenshot_20200313-141426](https://user-images.githubusercontent.com/1407489/76661194-041ffa80-6538-11ea-82d7-33e712caa4b3.png)

**Comment by RyanTG** [comment]
Now that I think about it, the recent activity stream comes straight from the api as a string. So I partially lead you astray! We’d have to add the delimiter to the score: https://github.com/scottwainstock/pbm/blob/f5cd2a4960166865faf9ea7b3379d9acf7c2d7c3/app/models/machine_score_xref.rb#L29

I’ll dig into it. But maybe like: https://github.com/scottwainstock/pbm/blob/11eb2445f2a712d195ca0b0fb61a43940aa6a249/app/views/users/profile.html.haml#L57

**Comment by RyanTG** [comment]
@beth said: Something like this? https://stackoverflow.com/questions/46516136/comma-separated-step-for-number-input-box

Thanks! That looks promising.

**Comment by bpoore** [comment]
@RyanTG, I thought you were talking about the input on the website. If you want to get commas in there, that'd would be a place to start.

We can certainly get this in the app.. it won't be the same as the link above though. I can make the update to the app or if @davidrs wants to take a stab at it, it will involve updating the value displayed <a href="https://github.com/bpoore/pbm-react/blob/master/app/screens/MachineDetails.js#L166">here</a>. Might be cleanest to make it a function we could call in other places so rather than `value={this.state.score}`, it would be something like `value={withCommas(this.state.score)}` where withCommas has the regex to add commas.

**Comment by RyanTG** [comment]
Sorry about the confusion. I got sloppy. But now that you mention it, we should add this to the website, too! So thanks!

**Comment by bpoore** [comment]
https://github.com/bpoore/pbm-react/commit/d9af3afee191149b89be9672ce5f424485bb53f9

**Comment by RyanTG** [comment]
Re-opening. This is currently not working on Android. Works fine on iOS.

**Comment by bpoore** [comment]
[fix for android](https://github.com/bpoore/pbm-react/compare/3237c66fb722...d2be792d68ce)
