### ISSUE TITLE
When map is moved, do not auto-refresh, but instead add a "search this area" button

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#319]

**Comment by bpoore** [comment]
I've been working on this. Updating the map to use this approach seems to be working great and was easy to do. There's more to do to make it all work quite right though since we have search... now the 'update search' is showing up when we've navigated the map due to search, but don't want to prompt the user about updating their search yet. Going to take a bit for me to get that cleaned up, but overall making progress.

**Comment by RyanTG** [comment]
Cool!

Yeah, I was thinking there would be trickiness with some of those cases.

**Comment by RyanTG** [comment]
Solved using `isGesture` from react-native-maps 0.28.0
