### ISSUE TITLE
Have the search bar show your current search

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#324]
I know we previously found that this wasn’t possible. But, making this issue just in case we want to revisit it and we figure out a solution.

**Comment by bpoore** [comment]
@RyanTG, let me know what you think of [this](https://github.com/bpoore/pbm-react/compare/have-search-bar-show-most-recent-search?expand=1). It's hard to have it be perfect, but this takes the last selected display value and starts the search bar out with that text while maintaining the `most recent searches`. Overall I like it, an example of where I don't love this:
* user's most recent search was Seattle (region)
* user goes to search and Seattle is populated in the search bar with the most recent completed searches otherwise
* adjust the Seattle query, now we are explicitly searching for Seattle and getting additional Seattle-like values that weren't initially showing

I don't know that folks would notice or care, but thought it was worth bringing up before merging. What do you think?

![IMG_6132](https://user-images.githubusercontent.com/7720282/115499073-9a3a5000-a223-11eb-8b0d-c299bc0589cc.jpeg)
![IMG_6133](https://user-images.githubusercontent.com/7720282/115499083-9dcdd700-a223-11eb-8f84-a2d3acd554cd.jpeg)

**Comment by RyanTG** [comment]
This is cool and interesting. But... I hate to say it but once again I did a poor job of explaining what I was thinking. I actually meant the searchbar on the map screen, not on the search screen :(

So:
- User searches for Seattle
- Map loads with Seattle, and the searchbar on the map shows "Seattle"

I hadn't considered what you just did. But, I think I like it! Those drawbacks you mentioned don't bother me.

**Comment by bpoore** [comment]
Ohhhhhh.... 

Is there an example app where this behavior is occurring? We would have the search bar populated with the last search a user made, but only since opening the app? I can think on this, but as a user, I think it could be weird to open the app up to your current location, but see the search bar say a specific location or a city, region, whatever that's not where the map currently is. If this is an existing pattern in other apps, I'd like to see it in action... especially the behavior with app startup vs foregrounding, etc to know when to clear out the content. 

Would the search content clear if the user updates their search area? 

We may be able to figure out something... just executing it well may require some thought

**Comment by bpoore** [comment]
Maybe this is what you wanted all along, but my initial inclination would be to try to wire up something that:
* search bar on map is initially the default text
* user performs a search, then the search result is populated in the search bar
* user moves map and search bar is cleared

I'm not sure how much is possible because the Search component isn't explicitly part of the Map component, so there may be some technical hurdles, but once we have targeted the desire behavior, I will give it a shot.

**Comment by RyanTG** [comment]
That is what I was thinking, except for the last point. For an example, check out google maps. Blank (placeholder text) when you first open, then the search text is in there and it stays in there if you move the map. Maybe we should clear it if you click the “search this area” refresh button.

**Comment by bpoore** [comment]
@RyanTG, let me know what you think about [this](https://github.com/bpoore/pbm-react/commit/db057b86ca5de168f4da4d91db705c4fe3f14042).

**Comment by RyanTG** [comment]
Feedback on this branch:

- I'm not loving the search input form showing your last search. 1) when I start a brand new session, the last search is sitting in there, and I found that disorienting. And 2) I can't think of a situation where I would want the input to be pre-filled like that. I imagine that I'll backspace or x out of it every time. What are your thoughts? I know you did a lot of work to get that functionality.
- If I search an area, like "Glendale, CA". The map kinda pans down when it first loads Glendale, causing the "Search this area" button to pop up. Is there a way to exclude it from popping up in this case (until the user has actually moved the map with their finger)?

At one point I had a weird map glitch after looking up a specific location then pressing back to go back to the map. But I can't replicate it.

I definitely like the placeholder text on the map showing your current search! Looks nice.

**Comment by bpoore** [comment]
None of it was that much work. I will remove the last search thing. I had thought that's what you were wanting when I did that initially. Considering it is available to be clicked from the list of recent searches, it is redundant to have it there. 

As for your 2nd point, that's what I spent a lot of time trying to nail down. I have a feeling it is happening due to changing the 0.001 to 0.0001 for the coordinate check and that is why that's happening. There are map shifts that we can't reliably account for it seems. I will try messing with it more, but I believe that is the tradeoff we are making by having increased sensitivity. Maybe it could be something in-between like 0.005 and work for our needs better.

**Comment by RyanTG** [comment]
Instead of using deltas to determine if the map was moved, can we use something like on “onPanDrag” (which I believe is android only)? 

There is discussion about this concept here: https://github.com/react-native-maps/react-native-maps/issues/2756

Looks like “did user move the map” was added last month: https://github.com/react-native-maps/react-native-maps/commit/84cd0c439c38d1757abdf9dae690b11488f214db

Expo SDK 41 did not include an RNMaps update. But perhaps it’s possible to get the version that includes this commit by pointing to that exact commit in pacskge.json?

`You can still set the github link to the PR's commit with the feature as a dependency in your package.json`

Anyway, just thinking out loud. It would probably be a big change anyway.

**Comment by bpoore** [comment]
Updating react-native maps to 0.28.0, we are getting the `isGesture` property for `onRegionChange` and `onRegionChangeComplete`, though the value appears to always be `undefined`. Not sure what I'm doing wrong 🤔

**Comment by RyanTG** [comment]
I saw one other issue saying this same thing. Maybe it’s not ready for prime time.

**Comment by RyanTG** [comment]
I have been unable to replicate the jerky issue when I add this check https://github.com/RyanTG/pbm-react/commit/47aa7fa76e653e786865d9eaf3d47f5b2b53c215

I'll test more. Also, in that commit, I don't really know if changing that function to be called `onRegionChangeComplete` is actually making a difference. That's just something I was trying out, and I forgot to revert back.

Taken from https://github.com/react-native-maps/react-native-maps/issues/846#issuecomment-275232672
