### ISSUE TITLE
Confirm button - update the info when clicked

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#33]
Not sure if it's an Expo problem for me, or a real problem.

Steps:
- Lookup a location, click the "Confirm" button

Result:
- The date doesn't update in front of my eyes. It _does_ update if I reload expo (I haven't tried simply going back to the map, and then reopening the location).
- And there's no toast message saying "thanks for confirming." I do see that message in the console log, but not on my phone.

**Comment by bpoore** [comment]
This is a real problem- I know what this issue is here and will be pushing up a fix. 

A toast message, interesting idea! I was planning to implement a modal like the existing app, but looking into a toast notification sounds good. I will start with the modal in the interest of getting this done for now.

**Comment by bpoore** [comment]
bd208cbe01fe475215b4986fc9bbec8a76beacd1

Here it is as a modal. Still need to work out what to show / what happens if there is a server error or the user isn't logged in.

**Comment by RyanTG** [comment]
I like the modal!
