### ISSUE TITLE
Location Details - phone number is producing an error when clicked.

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#35]
Phone number is a link, but it’s producing an error when clicked. It should open up the phone's call dialog.

https://github.com/bpoore/pbm-react/blob/master/app/screens/LocationDetails.js#L145

perhaps `openURL` is the wrong thing to use... but that's what I found when I looked it up!

**Comment by bpoore** [comment]
openURL was right, just needed a telephone specifier as well. This is working for me when running from my phone now. It's not working from the iOS simulator, but I'm hoping that since it's working from my phone, we're ok (I don't see a phone app on the iOS simulator). Close out if you agree and can confirm the phone prompt is now working. 

c670cf864d778ae3d2f5b5639b355a5836e56e49

**Comment by RyanTG** [comment]
Ahhh, nice. Thanks!
