### ISSUE TITLE
Picker is deprecated

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#351]
https://reactnative.dev/docs/picker

Expo recommends using https://github.com/react-native-picker/picker

We only use a picker on the SuggestLocation screen for choosing a country. Right now we are checking for platform and showing either a picker or a modal. And the Android picker is really tough to style.

**Comment by bpoore** [comment]
I've been messing around with this. The new picker looks and acts the same as the deprecated picker. We are still unable to style the picker itself when in the mode to make a selection. This appears to be using a native component under the hood. I suspect that we would have to eject our app and style the native picker if we want to style this thing (unless I'm missing something?). I'm wondering if we should use the approach we have with selecting machines, locations types, etc? Upsides being it would match some of our existing ways we have the user make choices.... plus it would be a pretty easy thing to slide in. Thoughts?

**Comment by RyanTG** [comment]
I’d definitely be into styling it like those other lists!

**Comment by bpoore** [comment]
[Branch](https://github.com/bpoore/pbm-react/compare/update-picker?expand=1)

Includes sending the country code rather than country name in the request payload:
<img width="423" alt="Screen Shot 2021-08-16 at 9 51 36 AM" src="https://user-images.githubusercontent.com/7720282/129601279-225e20d7-5b9c-44aa-82fa-1ddeaa3b7e56.png">
<img width="493" alt="Screen Shot 2021-08-16 at 9 52 39 AM" src="https://user-images.githubusercontent.com/7720282/129601290-e8d54489-d56e-47d9-aec7-7b5c8d6ae9d0.png">

**Comment by RyanTG** [comment]
Just tested. Seems great! This will be really nice to have fixed (the country code). It was an annoyance - and I didn't even realize it was an app issue. I thought it was a website issue).

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/372/commits/951e9467272cbd89620df15fdb0b172a3e46a57f
