### ISSUE TITLE
Password Reset = Infinite Loop

### ISSUE THREAD

**Issue by newcrunchysue** [bpoore/pbm-react#355]
Click reset password on login screen, get an email containing link to that same reset password screen, ad infinitum.

**Comment by RyanTG** [comment]
Thanks. 

@bpoore Here's my take:

On the website, there is a "forgot your password" screen, as well as a "now type in your new password" screen (that you get to via a link in email).

https://pinballmap.com/users/password/new
https://pinballmap.com/users/password/edit?reset_password_token=blahblah

We made a mistake in the "deep link" in the app for the password reset screen: https://github.com/bpoore/pbm-react/blob/master/app/screens/SignupLogin.js#L115

Right now it's looking for the string "password" in the url, and then sending users to the Forgot your Password screen in the app. But since both urls above contain "password" that means it's sending users back to that same screen when they click the email link.

On top of that, we don't actually have a "new password" screen in the app (only a reset password screen). So we either need to add a new password screen and adjust the deep link to go to the correct screen, or remove the deep link for that string.

**Comment by RyanTG** [comment]
Looking at this comment of mine - https://github.com/bpoore/pbm-react/issues/237#issuecomment-725736884 - it looks there isn't a way to say "include all urls (wildcard) EXCEPT these couple ones." So that's why we were trying to match as many urls as we could. That's a bummer. But I think what this means is that we need to make a "New Password" screen in the app that uses https://pinballmap.com/users/password/edit?reset_password_token=blahblah (the token is in the url).

**Comment by RyanTG** [comment]
In terms of whitelist/blacklist:

**Whitelist:** 
- all region paths
- /map
- /saved
- /suggest


**Blacklist:**
- /users* (because this is where login/reset/new are. /profile is also under here, which we would be ok to include as a deep link - but oh well)
- /store
- /app
- /faq (the faq on the website is different than on the app)
- /privacy (we link to this website url in the app)
- /admin
- /donate
- /*/flier
- /*/high_rollers
- /location_machine_xrefs.rss
- /*/location_machine_xrefs.rss
- /*/machine_score_xrefs.rss
- /*/events.rss


**Misc:**
- /events are tucked within ${region_name}/events, and I don't want to add another 101 json entries just for this. So we'll keep that logic in the signuplogin screen.
- /about (same as above)
- /contact (same as above - actually, I don't think this will ever come up as a website path because we redirect /contact to /about)

**Comment by RyanTG** [comment]
The fix is now pending on both app stores.

https://github.com/scottwainstock/pbm/commit/a4dd87d0965ac57df51990602ffcfd31d2762644
https://github.com/bpoore/pbm-react/pull/358
