### ISSUE TITLE
Bug: If app was recently used, deep link doesn't always open to that location

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#376]
Sometimes the deep link doesn't work, and the app stays on the page you were on already. But then _sometimes_ clicking the deep link a second time will send you to the correct screen.

it's inconsistent. Not sure what the solution. But I'm guessing that using a new version of React Navigation might help.

**Comment by bmanturner** [comment]
If your listener that catches the deep link intent is only on your home tab (not a location page), then it might be that it only catches it when the users is on the home tab and doesn't when they're already looking at a location.

**Comment by bpoore** [comment]
I can reproduce this and see what the problem is. I have a hacky solution that I might push up if I can't find a better solution.

The problem boils down to, in the LocationDetails screen, we only fetch the [location details](https://github.com/bpoore/pbm-react/blob/master/app/screens/LocationDetails.js#L115) when the componentDidMount lifecycle hook is called. When you try to deeplink into a location when a different location is what the app is showing, we aren't fetching the new location details. We can put logic in the componentWillReceiveProps lifecycle hook to get a different location's details... it's kind of hacky, but it works. That might be a fine solution for now as overall I'd like to clean up all the hacky things in the componentWillReceiveProps, but I don't know how much effort that will take.

**Comment by bpoore** [comment]
https://github.com/bpoore/pbm-react/commit/27cbe25c766b384c7a422305771f07aebed3f33e

**Comment by RyanTG** [comment]
Resolved. Slipped into the 5.2.6 release.
