### ISSUE TITLE
Have mapview show ALL locations when searching a city

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#412]
If you type a city in the search - such as Westminster - and then choose a result, the map will only show locations that are within a fixed radius. This means that depending on the size of the city, some results will be off-map (and not loaded at all, thus not visible in List either).

I would like the results to include every location in the chosen city, with the map zoomed appropriately.

There is a pending API commit to help with this: `/api/v1/locations?by_state_id=CO;by_city_id=Westminster`

Where the query includes both the city and state, so we can get all the locations in that city.

In terms of the map's zoom, perhaps we could use the `fitToSuppliedMarkers` function. https://github.com/react-native-maps/react-native-maps/blob/1f47e5bbcb7b24f21e11108e73af19e17eaf84ff/docs/mapview.md

**Comment by bpoore** [comment]
[Branch](https://github.com/bpoore/pbm-react/tree/search-by-city-refactor) to play with. It seems to be working pretty well other than that depending on where locations are found in a city, the center of the city is often not centered. Here is a video with how some cities are looking:

https://user-images.githubusercontent.com/7720282/148663937-ee0ff712-c7c8-4a23-896b-6fb0064e8e16.mp4


On the staging db, we need to update PDX. There is at least one location clearly not in PDX which causes the search to show all of the USA. With this new city search approach, we will need to be sure the cities are correct or we'll get really weird results.

**Comment by bpoore** [comment]
For cities with one or just a couple locations that are fairly close together, we may want to keep the original default zoom? For instance, I feel like McMinnville looks better with the default zoom than the more zoomed in appearance we're getting with the new approach.

![simulator_screenshot_F3572C41-C6D2-49A6-B16F-CFE1BC144F15](https://user-images.githubusercontent.com/7720282/148664104-4d1bf715-e858-4ca5-b1bf-8b60e02c2b9f.png)
![Simulator Screen Shot - iPhone 12 Pro - 2022-01-08 at 16 06 14](https://user-images.githubusercontent.com/7720282/148664129-0c06eec2-ab0f-453e-8a40-346fe25f4a36.png)

Our default lat/lon deltas are typically set to 0.1. In this new case we're getting: 0.015, 0.0075 respectively. I feel like we're getting close if we allow for the larger deltas when we determine the value should be greater than 0.1 and set to a default of 0.1 otherwise?

**Comment by bpoore** [comment]
@RyanTG, I pushed up a new commit. We are now using the `no_details` flag and have a min lat/lon delta of 0.1 and an arbitrary max of 3 just to be sure we don't ever break the API with this endpoint.

Of note, particularly when testing with LA, I was missing locations in the southern portion of the map view. Updating [this](https://github.com/bpoore/pbm-react/compare/search-by-city-refactor?expand=1#diff-c56dde51d07cdbf46db99f3a4a8807ee59fce292d8f08d19116e38f7ace8b936L70) to be the calculated max view (lat or lon) rather than a radius, gets all the locations. I'm not sure why the math isn't working out correctly though. We may have to dive deeper into map math to make sense of this... personally, I am ok with requesting a larger search distance in the case of the requests where we account for zoom. I could be swayed into looking into it more if you want. You can test for yourself by changing back the viewable distance value when the branch is checked out locally for you.

**Comment by RyanTG** [comment]
Realized I never responded to the comment above this one. Though I think we chatted about it. To me, the 0.1 is now looking a little too far out when there are only a few locations. For example, the first city I searched for on this branch was "Winter Haven, FL". In that city, there are only two locations, and they're right next to each other.

What about: using the actual "fit", but for cases where there are only a few locations (e.g. the zoom is below X), doing the fit + zooming out a bit. So like, if the calculated zoom is 0.0075 then we do "0.0075 + 0.005" (that's probably not the best value to add). And that second number is a fixed value. So, it's a fit + a buffer, rather than a 0.1 min.

**Comment by bpoore** [comment]
In the provided images, this was already applying `delta * 1.10` to get a 10% buffer. It sounds like we want to go lower than 0.1 for the minimum zoom, but I wonder if we can still just use a static value still. If the 2nd value is a fixed number, we're essentially setting the minimum zoom to that threshold anyways? I agree we should likely reduce the default minimum zoom, but it's always going to be a balance of showing more map than we want to if the only locations are really close together or possibly having locations right at the edges of the map (like the McMinnville image with the locations at the extreme top and bottom of the screen). Given a choice between the two, I'd rather see more map of the city... if there aren't many locations in a city and you see the whole city when searching, to me it's more obvious there are only that handful of locations for that city.

**Comment by RyanTG** [comment]
Thanks for considering this carefully. I agree with you about the value of seeing the whole city (and not wondering if there's more just outside the super-zoomed in extent). Fixed value sounds good, and yeah, maybe a little lower than 0.1 would look good.
