### ISSUE TITLE
Recent Activity - Screen

### ISSUE THREAD

**Issue by RyanTG** [bpoore/pbm-react#94]
Sorry - I realized I didn't make an issue for this.

Screen that shows all the User Submissions within a 50 mile radius.

Submission types include:
- Machine added
- Machine removed
- Machine comment
- Machine score
- Updated location metadata
- Confirmed Location
- Added Photo (this is currently set as a "user submission" - but we have an issue for it https://github.com/scottwainstock/pbm/issues/912 @scottwainstock 

Each submission will display as a list item.

See mockup:

![recentactivity](https://user-images.githubusercontent.com/632682/48434062-97bb9e00-e72d-11e8-8ea4-cc286ad4a8df.jpg)
)

**Comment by bpoore** [comment]
@RyanTG, here is an initial start looking at this recent activity screen. It's a start, but I think we will need to request refinements regarding the responses coming from the API to be able to wrap this up. This is currently using the `submission` string provided from the API response. This will be easiest for the app to absorb if we can just use the string coming back in that field rather than trying to build the sentence with the various pieces of information coming back. I'm thinking we explicitly outline what the sentence looks like for each activity scenario then check in with Scott to see if that's possible on his end. We also need to request the lat / lon for the locations to be included if we want to include the distance. 

Part of why it'd be nice to have the API build the string to show if possible is that we will have a lot of matching to try to do to build the sentences app-side. For the most part that isn't an issue, but there's a good chance that what we have for locations in the map-state may not include a location coming back from this list because I don't think we have a way to guarantee we're querying exactly the same radius of locations. 

This is what the response objects currently look like:
<img width="965" alt="Screen Shot 2019-03-16 at 2 43 28 PM" src="https://user-images.githubusercontent.com/7720282/54482015-f0916500-47f9-11e9-83af-3bf96259bfe7.png">

Action items:
- Request lat/lon to be included in the response objects
- Decide on the desired formats for the `submission` string so we can reliably use the field

**Comment by RyanTG** [comment]
Sweet! Looks like a good start. I agree with you about the sentences coming from the API.

I'll work on them. 

My action items for this screen:
- make it a scrollview
- add icons
- style

**Comment by RyanTG** [comment]
Can we sort by most recent?

**Comment by bpoore** [comment]
We can show the array in reverse order if the array starts with the oldest entries first. We have done this in other places throughout the app.

**Comment by bpoore** [comment]
@RyanTG  06766d561fef4662d16509d0b7b075c91c560e96

This covers reversing the array coming back so most recent shows up first, a placeholder `Icon` with strings for each of the "event-types" I could find and adding an ActivityIndicator while searching so there isn't an brief image of no results while we're actually just waiting for the API response.

**Comment by RyanTG** [comment]
This is a in-progress comment, started yesterday, where I planned to document the format of the user submissions. Commenting now, and will edit or delete later.


Current format:

**new_condition** 

`User xtraball (gmail@gmail.com) commented on Judge Dredd at Pins Mechanical Co. (Downtown). They said: Was out of order/turned off`

Edit here
https://github.com/scottwainstock/pbm/blob/c66c9fd88db704e34d7ae555feb9ac25f3822728/app/models/machine_condition.rb

spec
https://github.com/scottwainstock/pbm/blob/6f0833582ba42d7f5e9e278abe4512c2b2e38545/spec/features/location_machine_xrefs_controller_spec.rb#L213
https://github.com/scottwainstock/pbm/blob/c66c9fd88db704e34d7ae555feb9ac25f3822728/spec/models/machine_condition_spec.rb#L19

**new_lmx**

User xtraball (donutjim@gmail.com) added The Munsters (Pro) to Pins Mechanical Co. (Downtown)



score

https://github.com/scottwainstock/pbm/blob/c66c9fd88db704e34d7ae555feb9ac25f3822728/app/models/machine_score_xref.rb#L29

https://github.com/scottwainstock/pbm/blob/2f2d57cff9c347e9f82d6e2650531349732c1af9/spec/requests/api/v1/user_submissions_controller_spec.rb#L22

**Comment by RyanTG** [comment]
@bpoore 

Can we limit the types of user submissions that show up in the activity feed?

**YES**

case 'new_lmx':
case 'new_condition':
case 'remove_machine':
case 'new_msx':
case 'confirm_location':


**NO**

case 'contact_us':
case 'suggest_location':
case 'delete_location':

**Comment by RyanTG** [comment]
What do you think about having a "filter" button up top, where you can limit the results to just one of the submission types?

**Comment by bpoore** [comment]
@RyanTG totally, I was going to get into that today. Do you have thoughts on the layout for that? Does the button open a modal with the possible filters? If a filter is selected, where does a user press to clear the filter?

**Comment by bpoore** [comment]
@RyanTG let me know what you think of this 3f4e1f38da9c84f8679d844dcd3409844fb25d28. We need some updated styles and you can make sure the wordings are as you would like.

**Comment by RyanTG** [comment]
Sweet! Initial styling. https://github.com/bpoore/pbm-react/pull/138/commits/ab17b02abcf02bec1a95681b659e72d93734f802

I'll still tweak it a little, and I need to check on android. 

I was thinking it might be cool if people could click on a listitem in Recent Activity and it opens the Location Details for the location that was edited.

**Comment by bpoore** [comment]
I was thinking that too. I think it feels more natural for something to happen if a ListItem is pressed. This commit takes care of the navigation a565336f8e0ece52f2430e25da4cb3edb63d4c32, but we need to add to the list of API updates we'd like to request for this screen that the location name be included (without it, the location name is not going to show up at the top of the screen like it does when getting to this screen from other means).

**Comment by RyanTG** [comment]
This issue is basically done. Last task for this issue is on the API-end. We need to update the API to pass on the user submission activity in a better way. It should include action type, location id, location name, and the sentence. The issue for that is here: https://github.com/scottwainstock/pbm/issues/1144

**Comment by RyanTG** [comment]
Closing. I had forgotten that this was still open when I created the new issue to address the last remaining issue https://github.com/bpoore/pbm-react/issues/189
